---
title: |
  | GetTogetheR 
  |
subtitle: |
  |
  | ChatGPT und R
date: | 
  |
  | Jonas Frost
  | jonas.frost@studserv.uni-leipzig.de
  |
  | Peter Kannewitz                       
  | peter.kannewitz@uni-leipzig.de
  |
  |              
  |              
  |                                                                                                      08. Juni 2023
fontsize: 9 pt
output: 
  beamer_presentation:
    includes:
      in_header: preambel.tex
    latex_engine: lualatex  
    slide_level: 2
header-includes: 
  - \AtBeginDocument{\title[GetTogetheR 1]{\vspace{1cm} GetTogetheR!}}
  - \AtBeginDocument{\author[Peter Kannewitz \& Jonas Frost]{ }}
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE)
```


## Ablauf

\begin{minipage}{\textwidth}
   \linespread{2}
   \tableofcontents
\end{minipage}
\vspace*{3cm}

## Motivation

- (J)

# Kurzeinstieg: ChatGPT 

- (P)

## Was ist ChatGPT?

# ChatGPT nutzen

## Möglichkeiten ChatGPT in einen R-Worflow zu integrieren


- WebApp 
  - chat.openai.com
  - Voraussetzungen: OpenAI Konto 
- R-Plugins (/Packages)
  - Voraussetzungen: Konto, gültigen API-Key
  - Einschränkung: Rate-Limit
  - https://cran.r-project.org/web/packages/chatgpt/index.html
  - https://github.com/jcrodriguez1989/chatgpt
  
## OpenAI API Zugriff  

- (P)
- Wie, Probleme, Pricing, Zeigen
  
## Wir zeigens Euch

- Prompts überlegen, die wir demonstrieren wollen
- Einfaches Beispielscript mit Plugin bearbeiten

# Ressourcen und Hilfe

## Nützliche Ressourcen zum Thema

- (P & J)

# Austausch

## Austausch

- Welche Erfahrung habt Ihr mit ChatGPT in Bezug auf R gemacht?
- Welche Nachteile könnte ein aktiver Gebrauch von Chat-GPT haben?
- ...

## 

\center\huge

Danke fürs Teilnehmen!



